import { chromium } from 'playwright'; import { BASE, OUT, TESTS, launchArgs } from './env.mjs';
const browser = await chromium.launch(launchArgs(['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream','--autoplay-policy=no-user-gesture-required']));
const ctx = await browser.newContext({viewport:{width:390,height:844}, isMobile:true, hasTouch:true, deviceScaleFactor:2, permissions:['camera','microphone']});
const m = await ctx.newPage(); const errs = []; m.on('pageerror', e => errs.push(e.message));
await m.goto(BASE+'/index3.html'); await m.waitForTimeout(2500); await m.evaluate(()=>localStorage.setItem('gg_lang','de')); await m.reload(); await m.waitForTimeout(2500);
const vid = await m.evaluate(()=>window.__tables.instructions[0].id);
await m.goto(BASE+'/index3.html#/rec/'+vid); await m.waitForTimeout(2500);
console.log('fallback hidden:', await m.$eval('#fb', e => e.hidden), 'cam playing:', await m.$eval('#cam', v => !v.paused && v.readyState >= 2));
await m.screenshot({path:OUT+'/shots/cap-idle.png'});
const box = await m.$eval('#shutter', e => { const r = e.getBoundingClientRect(); return {x:r.x+r.width/2, y:r.y+r.height/2}; });
const cdp = await ctx.newCDPSession(m);
await cdp.send('Input.dispatchTouchEvent', {type:'touchStart', touchPoints:[{x:box.x, y:box.y}]});
await m.waitForTimeout(2500); await m.screenshot({path:OUT+'/shots/cap-rec2.png'});
console.log('t=2.5 pill:', await m.$eval('.cap-pill', e => e.textContent.trim()), 'classes:', await m.$eval('#shutter', e => e.className));
await m.waitForTimeout(3500); await m.screenshot({path:OUT+'/shots/cap-rec6.png'});
console.log('t=6 pill:', await m.$eval('.cap-pill', e => e.textContent.trim()), 'classes:', await m.$eval('#shutter', e => e.className));
await m.waitForTimeout(3000); await m.screenshot({path:OUT+'/shots/cap-rec9.png'});
console.log('t=9 pill:', await m.$eval('.cap-pill', e => e.textContent.trim()), 'classes:', await m.$eval('#shutter', e => e.className));
await cdp.send('Input.dispatchTouchEvent', {type:'touchEnd', touchPoints:[]});
await m.waitForTimeout(2500);
console.log('after stop pill:', await m.$eval('.cap-pill', e => e.textContent.trim()), 'steps:', await m.evaluate(()=>window.__tables.instructions[0].data.steps.filter(s=>s.kind!=='chapter').length));
console.log(errs.join('\n')||'NO ERRORS');
await browser.close();
