import { chromium } from 'playwright'; import { BASE, OUT, TESTS, launchArgs } from './env.mjs';
const pre = process.argv[2] || 'a';
const browser = await chromium.launch(launchArgs([]));
const errs = [];
const shot = async (p, name, opts={}) => { await p.screenshot({path:`${OUT}/shots/${pre}-${name}.png`, ...opts}); };
const d = await (await browser.newContext({viewport:{width:1366,height:860}})).newPage(); d.on('pageerror', e => errs.push('D '+e.message));
await d.goto(BASE+'/index3.html'); await d.waitForTimeout(2500);
await d.evaluate(()=>{ localStorage.setItem('gg_lang','de'); });
await d.goto(BASE+'/index3.html#/'); await d.waitForTimeout(400); await d.reload(); await d.waitForTimeout(2500);
const vid = await d.evaluate(()=>window.__tables.instructions[0].id);
await shot(d, 'dash-projects');
await d.evaluate(()=>sessionStorage.setItem('gg_dash','all')); await d.goto(BASE+'/index3.html#/p/none'); await d.waitForTimeout(400); await d.goto(BASE+'/index3.html#/'); await d.waitForTimeout(900); await shot(d, 'dash-all');
await d.goto(BASE+'/index3.html#/p/f1'); await d.waitForTimeout(900); await shot(d, 'project');
await d.goto(BASE+'/index3.html#/edit/'+vid); await d.waitForTimeout(1500); await d.click('[data-tab="steps"]'); await d.waitForTimeout(600); await shot(d, 'editor', {fullPage:true});
await d.click('[data-tab="settings"]'); await d.waitForTimeout(400); await shot(d, 'editor-settings', {fullPage:true});
await d.goto(BASE+'/index3.html#/results/'+vid); await d.waitForTimeout(1200); await shot(d, 'results', {fullPage:true});
await d.goto(BASE+'/index3.html#/stats'); await d.waitForTimeout(1200); await shot(d, 'stats', {fullPage:true});
await d.goto(BASE+'/index3.html#/admin'); await d.waitForTimeout(1200); await shot(d, 'admin', {fullPage:true});
await d.evaluate(()=>{ localStorage.setItem('gg_nosess','1'); }); await d.goto(BASE+'/index3.html#/x'); await d.reload(); await d.waitForTimeout(1500); await shot(d, 'login');
await d.evaluate(()=>{ localStorage.removeItem('gg_nosess'); });
// mobile
const m = await (await browser.newContext({viewport:{width:390,height:844}, isMobile:true, hasTouch:true, deviceScaleFactor:2})).newPage(); m.on('pageerror', e => errs.push('M '+e.message));
await m.goto(BASE+'/index3.html'); await m.waitForTimeout(2500); await m.evaluate(()=>{ localStorage.setItem('gg_lang','de'); }); await m.reload(); await m.waitForTimeout(2500);
const vid2 = await m.evaluate(()=>window.__tables.instructions[0].id);
await shot(m, 'm-dash', {fullPage:true});
await m.goto(BASE+'/index3.html#/edit/'+vid2); await m.waitForTimeout(1500); await m.click('[data-tab="steps"]'); await m.waitForTimeout(600); await shot(m, 'm-editor', {fullPage:true});
await m.goto(BASE+'/index3.html#/rec/'+vid2); await m.waitForTimeout(1500); await shot(m, 'm-capture');
await m.evaluate(()=>{ window.__tables.instructions[0].status='published'; });
await m.goto(BASE+'/index3.html#/'); await m.waitForTimeout(600);
await m.goto(BASE+'/index3.html#/v/'+vid2); await m.waitForTimeout(1500); await shot(m, 'm-viewer-overview');
await m.click('.ch-tile[data-g="0"]'); await m.waitForTimeout(500); await shot(m, 'm-viewer-start');
await m.fill('#wname', 'Anna'); await m.click('#begin'); await m.waitForTimeout(800); await shot(m, 'm-viewer-step');
await m.click('#menu'); await m.waitForTimeout(400); await shot(m, 'm-viewer-side'); await m.click('#sclose');
await m.evaluate(()=>{ localStorage.setItem('gg_nosess','1'); }); await m.goto(BASE+'/index3.html#/x'); await m.reload(); await m.waitForTimeout(1500); await shot(m, 'm-login', {fullPage:true});
console.log(errs.join('\n')||'NO ERRORS');
await browser.close();
